### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [toydotgame/old-google#5]
I see that it hasn't been updated in quite a while now

**Comment by toydotgame** [comment]
It's only been since March since the last commit, which isn't even the biggest gap between commits I've made:
![image](https://github.com/toydotgame/old-google/assets/64190512/2a05b9a5-5a2a-4376-9a6e-3943d59a37b6)

I'm just one person and this is a fairly simple single-file code project. Progress is slow because the singular known issue in the current version (the `margin-top` of the logo being removed by the script when it replaces the logo, causing the logo to be at the top of the page rather than aligned to the middle of the screen (only really noticeable in fullscreen)) is relatively low-priority.

If you have found another issue, please open an issue here on GitHub for it. Otherwise, the addon works; if it ain't broke, why fix it? It's not like there's much extra optimisation I could do anyway.

**Comment by IdkWhatToCallMe123** [comment]
whoops sorry for that didn't check that properly my bad
