### ISSUE TITLE
Current logo gets loaded in briefly

### ISSUE THREAD

**Issue by tempo660** [toydotgame/old-google#7]
When I go to google.com, I can for a split second see the current logo, before it is then replaced by the classic logo. Is it now possible to reorder the priority so the classic logo takes prescience, or to block the current logo or something?

**Comment by toydotgame** [comment]
I might consider running the replacement script at [`document_start`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extensionTypes/RunAt) rather than `document_end`, and then have a wait function in the JS which waits until a logo element is downloaded before running replacement (as not waiting after `document_start` will cause replacement to run on nothing).

I understand that on slow internet that the new logo may be shown for a long time due to slow loading delaying the `document_end` "trigger." The JS function I proposed is my best idea on how to approach this and is definitely a TODO after I'm done working on my current project of the UA alt. layout feature.

**Comment by toydotgame** [comment]
Fixed in [`20aee38`](https://github.com/toydotgame/old-google/commit/20aee389a745040a105c5671ca93b10cd7d40b62) and [`fba27b6`](https://github.com/toydotgame/old-google/commit/fba27b6dbaf0d8a864fb49054eae574e4e4c9a1e). The favicon and logo replacement code is run by a `MutationObserver` now, which starts waiting for the logo element to be loaded immediately after the page starts loading (instead of waiting for absolutely everything on the page to finish processing).
